-- Generated by tools/ibmi/ddl.py in github.com/wesGates/demand-forecasting from src/tables.py.
-- Do not edit. Change src/tables.py and regenerate.

CREATE TABLE WKG2.FORECAST (
    as_of DATE NOT NULL,
    id VARCHAR(40) NOT NULL,
    item_id VARCHAR(20) NOT NULL,
    store_id VARCHAR(8) NOT NULL,
    method VARCHAR(40) NOT NULL,
    horizon INTEGER NOT NULL,
    target_date DATE NOT NULL,
    forecast DECIMAL(15, 6) NOT NULL,
    fallback SMALLINT NOT NULL,
    code_digest VARCHAR(64) NOT NULL,
    made_at TIMESTAMP NOT NULL,
    PRIMARY KEY (as_of, id, method, target_date)
);

CREATE TABLE WKG2.SALES (
    id VARCHAR(40) NOT NULL,
    item_id VARCHAR(20) NOT NULL,
    store_id VARCHAR(8) NOT NULL,
    date DATE NOT NULL,
    units INTEGER NOT NULL,
    PRIMARY KEY (id, date)
);

CREATE TABLE WKG2.SUGGESTED (
    as_of DATE NOT NULL,
    id VARCHAR(40) NOT NULL,
    item_id VARCHAR(20) NOT NULL,
    store_id VARCHAR(8) NOT NULL,
    horizon INTEGER NOT NULL,
    target_date DATE NOT NULL,
    forecast DECIMAL(15, 6) NOT NULL,
    source VARCHAR(40) NOT NULL,
    PRIMARY KEY (as_of, id, target_date)
);
